name: Build

on: [push, pull_request]

env:
  # CIBW_BUILD_VERBOSITY: 1
  CIBW_TEST_COMMAND: python -c "import sys, cpufeature; sys.exit(0 if cpufeature.test().wasSuccessful() else 1)"
  CIBW_SKIP: "*-macosx_universal2"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels for CPython 3.8
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"

      - name: Build wheels for CPython 3.10 and above
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-*"

      - run: ls ./wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build sdist
        run: |
          python -m pip install build
          python -m build --sdist .
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz


  merge_artifacts:
    name: Merge all wheelhouse artifacts
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: dist
          delete-merged: true
